name: C++ CI with GTest

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ cppcheck clang-tidy clang-tools

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Build Project
      run: cmake --build build

    - name: Run cppcheck
      continue-on-error: true
      run: cppcheck --enable=all --inconclusive --std=c++17 .

    - name: Run clang-tidy
      continue-on-error: true
      run: run-clang-tidy -p build

    - name: Run Google Tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Fix paths in compile_commands.json for SonarCloud
      run: |
        sed -i 's|/home/runner/work/RobotCleaner/RobotCleaner|/github/workspace|g' build/compile_commands.json

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        args: >
          -Dsonar.projectKey=hahahanjihun_RobotCleaner
          -Dsonar.organization=hahahanjihun
          -Dsonar.sources=src
          -Dsonar.tests=tests
          -Dsonar.cfamily.compile-commands=build/compile_commands.json
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}