name: C++ CI with GTest

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSVC
      uses: microsoft/setup-msbuild@v2

    # cppcheck
    - name: Run cppcheck
      continue-on-error: true
      run: |
        choco install cppcheck -y --force
        cppcheck --enable=all --inconclusive --std=c++17 . || true

    # clang-tidy
    - name: Run clang-tidy
      continue-on-error: true
      run: |
        choco install llvm -y
        Get-ChildItem -Recurse -Filter *.cpp | ForEach-Object {
          clang-tidy $_.FullName -- -std=c++17
        }

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build Project
      run: cmake --build build

    - name: Run Google Tests
      run: |
        cd build
        ctest --output-on-failure

    # SonarCloud
    - name: SonarCloud Scan
      continue-on-error: true
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        args: >
          -Dsonar.projectKey=hahahanjihun_RobotCleaner
          -Dsonar.organization=hahahanjihun
          -Dsonar.sources=.
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}